name: My Tech Blog
description: 
meta_description: 

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: 'https://dianazv.github.io'
google_analytics: 'G-1PQC0HY1M1
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://dianazv.github.io'
author:         'Diana'
